

<script type="text/javascript">

//	<!--/* ========================= BROWSER SNIFFER ========================= */-->

	console.log('window.location.href = ' + window.location.href);

//	var thisWidth = (window.innerWidth > 0) ? window.innerWidth : screen.width;
//	console.log('thisWidth = ' + thisWidth);

	console.log('window.innerWidth = ' + window.innerWidth);
	console.log('screen.width = ' + screen.width);



//	<!--/* ========================= GOOGLE ========================= */-->

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-62347464-1']);
	_gaq.push(['_setDomainName', '.mariahcareybeauty.com']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	})();

</script>


