<div id="footer">
        <p>
            <a href="http://mariahcarey.com/help" target="_blank">Help</a>&nbsp;|
            <!--<a href="https://mariahcarey.com/user/register" target="_blank">Newsletter</a>&nbsp;|-->
			<a onClick="return popUp('../../unsubscribe.php')" href="../../unsubscribe.php">Unsubscribe</a>&nbsp;|
            <a onClick="return popUp('../../PrivacyPolicy.php')" href="../../PrivacyPolicy.php">Privacy Policy</a>&nbsp;|
            <a onClick="return popUp('../../TermsOfUse.php')" href="../../TermsOfUse.php">Terms of Use</a>&nbsp;
            <!--<a href="http://www.livenation.com/Mariah-Carey-tickets/artist/767870" target="_blank">Mariah Carey Concert Tickets</a>-->
			<br><i>Mariah Carey</i> is a trademark of Automatic Princess Holdings LLC and is used with permission. ©2015 EA Fragrances Co.
        </p>
    </div>
