<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Privacy Policy | Mariah Carey Beauty</title>
	<link href="_css/reset.css" rel="stylesheet" type="text/css" />
	<link href="_css/popup.css" rel="stylesheet" type="text/css" />
	<? include 'includes/google.inc'; ?>
</head>
<body class="popup">
<h1>Mariah Carey Beauty – PRIVACY POLICY</h1>
<p>Elizabeth Arden, Inc. ("we" or "Elizabeth Arden") has created this Privacy Policy to demonstrate our commitment to your privacy. This policy sets forth our information collection and use practices only for the website located at www.mariahcareybeauty.com (the "Site") and does not apply to any other Elizabeth Arden website or service. If you do not agree to the terms and conditions of this Privacy Policy, you may not access or otherwise use this Site. We also direct you to our Terms of Conditions and Use statement, which governs your use of the Site.</p>
<p>INFORMATION ELIZABETH ARDEN COLLECTS</p>
<p>1. Personally Identifiable Information.</p>
<p>When using the Site, we may ask you to provide us with certain personally identifiable information ("PII"), which is information that could reasonably be used to identify you personally. For example, we may seek PII when you register with us or at other times, such as if you choose to participate in a game, chat room, electronic bulletin board, contest, sweepstakes, or other promotional event. PII can include your name, address, e-mail address, telephone number or mobile telephone number, and date of birth. We may also ask you to create a screen name and/or a password, where applicable, and provide us with demographic information (such as information about your age or gender), information regarding your interests, or similar information.</p>
<p>You may also have the opportunity to provide us with the PII of a friend (or for a friend to provide such information about you), such as a name or an e-mail address, if you choose to e-mail a friend an electronic greeting card or participate in another special feature on the Site. The e-mail addresses you supply to us for these purposes will not be used to send to you (or to your friend) other e-mail communications, including promotional materials, and we will use reasonable efforts to delete such information from our database, unless otherwise disclosed at the time you provide such information.</p>
<p>PII will only be collected when it is voluntarily provided to Elizabeth Arden. You can always choose not to provide certain information, but then you may not be able to take advantage of or participate in certain features of the Site.</p>
<p>2. Non-personally Identifiable Information.</p>
<p>We may also collect from you non-personally identifiable information, such as an IP host address, the pages viewed, the browser type, the Site usage, and other data which do not identify any individual ("Aggregate Information"). When your computer contacts our web servers (for example, when you visit the Site, view an HTML e-mail, or download an interactive desktop from the Site), Aggregate Information may be collected automatically. We also may determine the applicable technology available to serve you the most appropriate version of a web page, e-mail or similar service.</p>
<p>3. COOKIES AND TRACKING TECHNOLOGY</p>
<p>The Site may use browser "cookies." Cookies are pieces of information that may be placed on your computer by a website for the purpose of facilitating and enhancing your communication and interaction with a particular website. We may use cookies to customize your visit to the Site and for other purposes to make your visit more convenient or to enable us to enhance our service. For example, we may use cookies when we conduct polls or contests to limit multiple responses and registrations, or we may use cookies to track usage patterns on the Site or to analyze web activity. You may stop or restrict the placement of cookies on your computer or remove them from your browser by adjusting your web browser preferences. If you do so, you may still use the Site, but it may interfere with some of its functionality. We do not use cookies to automatically retrieve PII from your computer without your knowledge.</p>
<p>In addition to cookies, the Site uses a variety of technical methods for tracking purposes, including web beacons. Web beacons are small pieces of data that are embedded in images on the pages of websites. Elizabeth Arden also uses these technical methods to analyze the traffic patterns on the www. mariahcareybeauty.com website, such as the frequency with which our users visit various parts of the Site.</p>
<p>HOW ELIZABETH ARDEN USES THE INFORMATION IT COLLECTS</p>
<p>1. Personally Identifiable Information.</p>
<p>PII submitted to us is used to deliver the services you request, to keep you informed about changes affecting our services or your account, to inform you of products, including product launches, other services, games or offers from Elizabeth Arden (such as through personalized messages) and its affiliated companies in which you might be interested, and to improve and enhance the Site and services. If you provide PII to Elizabeth Arden, we will take all reasonable and appropriate steps to protect it from unauthorized disclosure.</p>
<p>In addition to the uses of PII explained above, by giving Elizabeth Arden your telephone and/or mobile telephone number, you expressly authorize Elizabeth Arden to contact you by telephone and send you text messages, if the number you provide is for a mobile telephone. Please be aware that your wireless carrier may charge you for the receipt of such messages, and other charges may apply. If you do not want to receive such messages, you should not provide us with your telephone or mobile telephone number. You may opt-out of receiving such messages by following the opt-out procedures below.</p>
<p>We may conduct joint promotions with other companies. We may share with our promotional partners (and their service providers) certain PII as necessary to conduct the promotion. We will not share this information with our promotional partners for any other purpose unless you provide us with your consent to do so.</p>
<p>We may combine the information we collect about you at the Site with information available to us from other sources. For example, you may provide PII to us at other Elizabeth Arden websites, or our co-promoter or sponsors may provide us with information, including PII, about users who choose to participate in a promotional opportunity the co-promoter or sponsor is offering in connection with Elizabeth Arden.</p>
<p>We will never disclose your PII to any third party who is not affiliated with, a business partner of or a sponsor of Elizabeth Arden without your express consent, except in the following circumstances: (i) in connection with the sale or merger of Elizabeth Arden or the division responsible for such services, (ii) as required by courts or administrative agencies, and (iii) to the extent required to permit us to investigate suspected fraud, harassment or other violations of any law, rule or regulation, the Site rules or policies, or the rights of third parties or any other suspected conduct we deem improper.</p>
<p>2. Non-Personally Identifying Information.
<p>Elizabeth Arden may use and disclose Aggregate Information to improve and enhance your experience on the Site and for other purposes. For example, from time to time, we may use and share Aggregate Information with third parties to show general demographic and preference information among users of the Site. In these circumstances, the shared information will neither contain nor be linked to any PII.</p>
<p>SPECIAL NOTICE REGARDING CHILDREN UNDER 13 YEARS OLD </p>
<p>Elizabeth Arden recognizes the sensitivity of PII concerning children under the age of 13 and therefore provides this notice. Elizabeth Arden is committed to complying with all applicable laws and regulations regarding children, including the Children’s Online Privacy Protection Act ("COPPA"), which does not allow the collection of any PII from anyone under the age of 13 without a parent’s or guardian’s consent.</p>
<p>Therefore, in compliance with COPPA, the Site is not directed to children under the age of 13, and Elizabeth Arden does not knowingly collect PII from children under 13 years of age. If you are under 13 years of age, do not send any information about yourself to Elizabeth Arden. When Elizabeth Arden becomes aware that personal information from a child under 13 has been collected without such child’s parent’s or guardian’s consent, we will use all reasonable efforts to delete such information from our database.</p>
<p>OPT-OUT POLICY</p>
<p>If you wish for us to remove your PII from our active records, please go to the "Click here to unsubscribe" link on www. mariahcareybeauty.com. Please be aware that we will process your request within a reasonable time after receipt. You should also be aware that we are not responsible for removing your PII from the lists of any third party who has previously been provided with your information in accordance with this policy, such as a business partner. In addition, your ability to opt-out from receiving marketing and promotional material does not change our right to contact you regarding your use of the Site or changes to our Privacy Policy, Terms and Conditions of Use statement or other policy or terms that affect you and your use of the Site.</p>
<p>USER FORUMS </p>
<p>Please review our restrictions on use and guidelines for user forums in our Terms and Conditions of Use statement. In addition, please note that this Privacy Policy does not apply to any information you may disclose publicly in user forums (such as chat rooms, bulletin boards, or similar web pages). You should be aware that whenever you publicly disclose information about yourself online, including uploading photographs to the Site, that information could be collected and used by people you do not know. In addition, certain message boards (and similar user forums) may display IP addresses along with the message poster’s name and message. Elizabeth Arden bears no responsibility for any action or policies of any third party who collects any information users may disclose in user forums or other public areas, if any, on the Site. </p>
<p>SECURITY </p>
<p>The security of your PII is very important to us. However, due to the inherent open nature of the Internet, we cannot guarantee that communications between you and Elizabeth Arden, or information stored on the Site or our servers, will be completely free from unauthorized access by third parties such as hackers, and your use of the Site is at your own risk. We have put in place reasonable physical, electronic, and managerial procedures to safeguard the information we collect, including limiting access to the PII contained on our servers. Only those employees who need access to your information to perform their duties are authorized to have access to your PII. Elizabeth Arden also recommends that you keep your information safe by, for example, memorizing your password or securing it in a safe place (separate from your account information), logging out of your user account, and closing your web browser once you leave the Site. </p>
<p>LINKS TO AND FROM OTHER WEBSITES </p>
<p>The Site may contain links to other websites not maintained by Elizabeth Arden, and other websites may reference or link to the Site. These other websites may set their own cookies, collect data, solicit PII, and/or have their own privacy policies. We encourage you to be aware when you leave our Site and to read the privacy policies and terms and conditions of each and every website you visit. Elizabeth Arden is not responsible for the practices or the content of other such websites, expressly disclaims any statements or assertions made on such websites, and denies all liability associated with your use of, and the content on, other such sites. </p>
<p>CONSENT TO TRANSFER </p>
<p>The site is maintained in the United States of America. If you are located in the European Union, Canada or elsewhere outside of the United States, please be aware that any information you provide to us will be transferred to the United States. By using the Site, participating in any of our services, and/or providing us with your information, you consent to this transfer. </p>
<p>ACCEPTANCE AND CHANGES TO POLICY </p>
<p>By visiting the Site, you agree to the terms and conditions of the Privacy Policy. Elizabeth Arden reserves the right to change, modify, alter or otherwise update this Privacy Policy at any time without notice. We will post any changes here, so be sure to visit this page often. If at any time in the future we plan to use your PII in a way that differs from this policy, we will post such changes here and provide you the opportunity to opt-out of such differing uses. Your continued use of the Site after we post any changes to this Privacy Policy means you accept such changes. </p>
<p>CONTACT US </p>
<p>If you have any questions, comments or concerns about our privacy practices or this Privacy Policy, you may contact us at: contactus@mariahcareybeauty.com.</p>
<p>EFFECTIVE DATE </p>
<p>This Privacy Policy is effective and was last updated on January 5, 2006. </p>
<p>Copyright © 2012 Elizabeth Arden, Inc. All rights reserved. </p>
</body>
</html>
